packages:
  - frontend
  - backend
allowBuilds:
  '@nestjs/core': set this to true or false
  esbuild: set this to true or false
  puppeteer: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
