-- ============================================================
-- Script: sp_MantenimientoVias_ListarUsuarios
-- Descripción: Lista usuarios de acceso.tblusuarios para el
--              módulo Mantenimiento de Vías
-- Parámetros:
--   @codigo  VARCHAR(20) = ''  — Filtro por código de usuario
--   @zona    VARCHAR(50) = ''  — Filtro por zona
--   @estado  VARCHAR(10) = ''  — Filtro por estado (''=Todos, '1'=Activo, '0'=Inactivo)
--   @inicio  INT = NULL        — Paginación: inicio del rango. Si NULL, devuelve solo total
--   @final   INT = NULL        — Paginación: final del rango. Si NULL, devuelve solo total
-- Comportamiento:
--   - Si @inicio IS NULL: devuelve { total: N } — solo el conteo
--   - Si @inicio IS NOT NULL: devuelve filas paginadas con ROW
-- ============================================================
-- Pendiente: Ejecutar este script en la base de datos objetivo.
-- ============================================================
-- 
-- CREATE PROCEDURE [dbo].[sp_MantenimientoVias_ListarUsuarios]
--   @codigo  VARCHAR(20) = '',
--   @zona    VARCHAR(50) = '',
--   @estado  VARCHAR(10) = '',
--   @inicio  INT = NULL,
--   @final   INT = NULL
-- AS
-- BEGIN
--   SET NOCOUNT ON;
-- 
--   DECLARE @Temp TABLE (vlogin VARCHAR(100), nestado VARCHAR(10));
-- 
--   INSERT INTO @Temp
--   SELECT vlogin, nestado
--   FROM acceso.tblusuarios
--   WHERE (@codigo = '' OR vlogin LIKE '%' + @codigo + '%')
--     AND (@zona = '' OR 1 = 1)
--     AND (@estado = '' OR nestado = @estado);
-- 
--   IF @inicio IS NULL
--   BEGIN
--     SELECT COUNT(*) AS total FROM @Temp;
--     RETURN;
--   END;
-- 
--   SELECT vlogin
--   FROM (
--     SELECT vlogin,
--           ROW_NUMBER() OVER (ORDER BY vlogin) AS ROW
--     FROM @Temp
--   ) AS T
--   WHERE T.ROW BETWEEN @inicio AND @final
--   ORDER BY T.ROW;
-- END;
-- 
-- ============================================================
-- Nota: El SP se documenta aquí como script de referencia.
-- La ejecución contra la BD real se realiza fuera del alcance
-- de este cambio (DBAs / deployment pipeline).
-- ============================================================
