import { z } from 'zod';

// ── Guardar contribuyente (modal Nuevo Contribuyente) ──
// Mapea 1:1 los parámetros del SP Rentas.sp_Mcontribuyente @busc=1.

export const GuardarContribuyenteSchema = z.object({
  codigo: z.string().optional().default(''),
  id_pers: z.string().optional().default(''),
  id_docu: z.string().optional().default(''),
  num_doc: z.string().optional().default(''),
  nombres: z.string().optional().default(''),
  paterno: z.string().optional().default(''),
  materno: z.string().optional().default(''),
  id_dist: z.string().optional().default(''),
  tipourb: z.string().optional().default(''),
  des_urb: z.string().optional().default(''),
  tipovia: z.string().optional().default(''),
  des_via: z.string().optional().default(''),
  id_zona: z.string().optional().default(''),
  id_urba: z.string().optional().default(''),
  id_via: z.string().optional().default(''),
  referencia: z.string().optional().default(''),
  manzana: z.string().optional().default(''),
  lote: z.string().optional().default(''),
  sub_lote: z.string().optional().default(''),
  numero: z.string().optional().default(''),
  departam: z.string().optional().default(''),
  nestado: z.string().optional().default(''),
  motivo: z.string().optional().default(''),
  operador: z.string().optional().default(''),
  estacion: z.string().optional().default(''),
  id_tipocontri: z.string().optional().default(''),
  id_subtipocontri: z.string().optional().default(''),
  id_motivo_actualizacion: z.string().optional().default(''),
  tipo_interior_id: z.string().optional().default(''),
  tipo_edificio_id: z.string().optional().default(''),
  tipo_ingreso_id: z.string().optional().default(''),
  tipo_agrupamiento_id: z.string().optional().default(''),
  letra1: z.string().optional().default(''),
  letra2: z.string().optional().default(''),
  numero2: z.string().optional().default(''),
  nombre_ingreso: z.string().optional().default(''),
  nombre_agrupamiento: z.string().optional().default(''),
  nombre_edificio: z.string().optional().default(''),
  piso: z.string().optional().default(''),
  numero_interno: z.string().optional().default(''),
  letra_interno: z.string().optional().default(''),
  correo_e: z.string().optional().default(''),
  partida_defuncion: z.string().optional().default(''),
  fecha_defuncion: z.string().optional().default(''),
  telefono1: z.string().optional().default(''),
  anexo1: z.string().optional().default(''),
  telefono2: z.string().optional().default(''),
  anexo2: z.string().optional().default(''),
  flag_notificar: z.string().optional().default(''),
  idperfil: z.string().optional().default(''),
});

export type GuardarContribuyenteDto = z.infer<typeof GuardarContribuyenteSchema>;
